import { ScorableArchetype } from "./match-archetypes";

export interface ArchetypeDefinition extends ScorableArchetype {
  personalityLabel: string;
  description: string;
  clothingDNA: string;
  hairstyleDNA: string;
  shoesDNA: string;
  colorDNA: string[];
  avoidDNA: string;
  imagePromptTemplate: string;
}

const BASE_PROMPT = `A full-body fashion editorial photo of a {gender} model embodying the {personalityLabel} style. {bodyTypeHint} {faceShapeHint}. Outfit: {clothingDNA}. Shoes: {shoesDNA}. Colors: {colorDNA}. Hairstyle: {hairstyleDNA}. Avoid: {avoidDNA}. Clean studio background, soft natural light, no text, no user face, no transformation.`;

function defineArchetype(def: Omit<ArchetypeDefinition, "id" | "active">): ArchetypeDefinition {
  return {
    ...def,
    id: def.slug,
    active: true,
  };
}

export const MALE_ARCHETYPES: ArchetypeDefinition[] = [
  defineArchetype({
    slug: "clean-minimal",
    name: "Clean Minimal",
    personalityLabel: "Modern Minimalist",
    genderScope: "MALE",
    category: "Minimal",
    description: "Sharp basics, neutral palette, nothing extra.",
    keywords: ["minimal", "clean", "simple", "premium basics"],
    clothingDNA: "Tailored crew-neck tees, crisp oxford shirts, tapered chinos, dark selvedge denim, unstructured blazers.",
    hairstyleDNA: "Neat textured crop or classic side part, low maintenance.",
    shoesDNA: "Clean white leather sneakers, minimalist loafers, suede desert boots.",
    colorDNA: ["white", "light gray", "navy", "camel", "black"],
    avoidDNA: "oversized logos, busy patterns, heavy layering",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "smart-casual",
    name: "Smart Casual",
    personalityLabel: "Refined Professional",
    genderScope: "MALE",
    category: "Business Casual",
    description: "Polished enough for the office, relaxed enough for dinner.",
    keywords: ["modern", "refined", "office casual"],
    clothingDNA: "Knit polos, tailored trousers, unstructured blazers, merino layers, dark denim.",
    hairstyleDNA: "Clean taper with natural texture or slicked-back neat style.",
    shoesDNA: "Leather loafers, minimalist derby shoes, clean suede sneakers.",
    colorDNA: ["navy", "charcoal", "burgundy", "cream", "olive"],
    avoidDNA: "baggy jeans, loud graphics, athletic sneakers",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "old-money",
    name: "Old Money",
    personalityLabel: "Modern Gentleman",
    genderScope: "MALE",
    category: "Luxury Classic",
    description: "Quiet luxury built on heritage fabrics and timeless silhouettes.",
    keywords: ["quiet luxury", "classic", "heritage"],
    clothingDNA: "Cashmere crewnecks, tailored wool trousers, camel overcoats, crisp white shirts, fine-knit polos.",
    hairstyleDNA: "Classic side part, neatly groomed, medium length.",
    shoesDNA: "Dark leather loafers, polished oxford shoes, suede chukka boots.",
    colorDNA: ["navy", "camel", "cream", "bottle green", "burgundy"],
    avoidDNA: "logo-driven pieces, synthetic fabrics, overly tight or oversized fits",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "japanese-minimal",
    name: "Japanese Minimal",
    personalityLabel: "Tokyo Minimalist",
    genderScope: "MALE",
    category: "Minimal",
    description: "Relaxed proportions, muted tones, intentional layering.",
    keywords: ["japanese", "layering", "relaxed tailoring"],
    clothingDNA: "Wide-leg trousers, oversized shirts, longline cardigans, boxy blazers, natural fabrics.",
    hairstyleDNA: "Textured medium length, soft fringe, or sleek tucked-back style.",
    shoesDNA: "Minimal leather sneakers, Japanese loafers, suede slip-ons.",
    colorDNA: ["ivory", "charcoal", "sand", "slate blue", "black"],
    avoidDNA: "bright colors, rigid suiting, heavy branding",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "streetwear",
    name: "Streetwear",
    personalityLabel: "Urban Creative",
    genderScope: "MALE",
    category: "Urban",
    description: "Oversized silhouettes, bold references, contemporary attitude.",
    keywords: ["urban", "oversized", "street fashion"],
    clothingDNA: "Boxy tees, oversized hoodies, cargo pants, bomber jackets, statement outerwear.",
    hairstyleDNA: "Buzz cut, textured crop, braids, or messy fringe.",
    shoesDNA: "High-top sneakers, chunky runners, limited-edition collaborations.",
    colorDNA: ["black", "gray", "white", "neon accent", "earth tone"],
    avoidDNA: "slim-fit formal trousers, polished dress shoes, preppy patterns",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "business-formal",
    name: "Business Formal",
    personalityLabel: "Executive Presence",
    genderScope: "MALE",
    category: "Formal",
    description: "Boardroom-ready tailoring with commanding presence.",
    keywords: ["executive", "professional", "formal"],
    clothingDNA: "Two-piece suits, crisp dress shirts, silk ties, overcoats, pocket squares.",
    hairstyleDNA: "Neatly combed, classic business cut, clean neckline.",
    shoesDNA: "Polished oxford shoes, patent leather, premium leather derbies.",
    colorDNA: ["charcoal", "navy", "black", "white", "deep burgundy"],
    avoidDNA: "denim, sneakers, casual knits, loud patterns",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "preppy",
    name: "Preppy",
    personalityLabel: "Ivy League Gentleman",
    genderScope: "MALE",
    category: "Classic",
    description: "Collegiate classics with a clean, privileged attitude.",
    keywords: ["ivy league", "college", "classic"],
    clothingDNA: "Chambray shirts, chinos, cable-knit sweaters, navy blazers, rugby stripes.",
    hairstyleDNA: "Classic side part, medium length, clean and tidy.",
    shoesDNA: "Leather boat shoes, penny loafers, canvas sneakers.",
    colorDNA: ["navy", "burgundy", "cream", "kelly green", "white"],
    avoidDNA: "distressed denim, oversized streetwear, neon colors",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "workwear",
    name: "Workwear",
    personalityLabel: "Heritage Craftsman",
    genderScope: "MALE",
    category: "Utility",
    description: "Rugged utility pieces with honest fabrics and functional details.",
    keywords: ["utility", "rugged", "heritage"],
    clothingDNA: "Heavyweight chore coats, canvas trousers, flannel shirts, denim jackets, tool belts.",
    hairstyleDNA: "Short practical cut, slicked back, or medium textured style.",
    shoesDNA: "Work boots, moc-toe boots, leather derbies, canvas high-tops.",
    colorDNA: ["brown", "olive", "indigo", "tan", "charcoal"],
    avoidDNA: "shiny synthetics, slim dress pants, delicate fabrics",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "gorpcore",
    name: "Gorpcore",
    personalityLabel: "Outdoor Technologist",
    genderScope: "MALE",
    category: "Outdoor",
    description: "Technical outdoor gear worn with urban confidence.",
    keywords: ["outdoor", "technical", "functional"],
    clothingDNA: "Hardshell jackets, cargo pants, fleece layers, utility vests, technical backpacks.",
    hairstyleDNA: "Practical short cut, buzzed sides, or baseball-cap-ready medium length.",
    shoesDNA: "Trail-running shoes, technical sneakers, hiking boots.",
    colorDNA: ["olive", "black", "gray", "orange accent", "sand"],
    avoidDNA: "formal suiting, leather loafers, delicate knits",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "french-casual",
    name: "French Casual",
    personalityLabel: "Parisian Nonchalant",
    genderScope: "MALE",
    category: "Effortless",
    description: "Effortless Parisian style with undone elegance.",
    keywords: ["parisian", "effortless", "chic"],
    clothingDNA: "Breton stripes, linen shirts, tailored trousers, leather jackets, wool coats.",
    hairstyleDNA: "Tousled medium length, natural texture, relaxed side part.",
    shoesDNA: "White leather sneakers, suede chelsea boots, leather loafers.",
    colorDNA: ["navy", "white", "black", "camel", "gray"],
    avoidDNA: "oversized logos, bright neon, overly distressed denim",
    imagePromptTemplate: BASE_PROMPT,
  }),
];

export const FEMALE_ARCHETYPES: ArchetypeDefinition[] = [
  defineArchetype({
    slug: "minimal-chic",
    name: "Minimal Chic",
    personalityLabel: "Effortless Sophisticate",
    genderScope: "FEMALE",
    category: "Minimal",
    description: "Clean lines, premium materials, understated confidence.",
    keywords: ["minimal", "modern", "premium"],
    clothingDNA: "Structured blazers, silk blouses, wide-leg trousers, slip skirts, tailored coats.",
    hairstyleDNA: "Sleek low bun, straight middle part, or polished ponytail.",
    shoesDNA: "Pointed flats, minimalist ankle boots, kitten heels.",
    colorDNA: ["black", "white", "camel", "gray", "navy"],
    avoidDNA: "busy prints, excessive jewelry, loud logos",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "korean-soft-minimal",
    name: "Korean Soft Minimal",
    personalityLabel: "Seoul Soft",
    genderScope: "FEMALE",
    category: "Soft",
    description: "Gentle layers, muted pastels, approachable femininity.",
    keywords: ["korean", "soft", "feminine"],
    clothingDNA: "Soft knit tops, pleated midi skirts, oversized cardigans, straight-leg jeans, trench coats.",
    hairstyleDNA: "See-through bangs, soft waves, low ponytail, or natural black hair.",
    shoesDNA: "Chunky loafers, canvas sneakers, low-block heels, mary janes.",
    colorDNA: ["ivory", "beige", "dusty pink", "soft blue", "gray"],
    avoidDNA: "aggressive tailoring, dark gothic tones, heavy makeup styling",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "french-chic",
    name: "French Chic",
    personalityLabel: "Parisian Muse",
    genderScope: "FEMALE",
    category: "Effortless",
    description: "Timeless elegance with a relaxed, romantic edge.",
    keywords: ["parisian", "elegant", "effortless"],
    clothingDNA: "Silk camisoles, high-waist jeans, tailored blazers, ballet flats, trench coats.",
    hairstyleDNA: "Tousled bob, curtain bangs, messy bun, or natural waves.",
    shoesDNA: "Ballet flats, block-heel ankle boots, leather loafers.",
    colorDNA: ["black", "white", "denim blue", "camel", "red accent"],
    avoidDNA: "overly coordinated outfits, heavy logos, neon colors",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "old-money-feminine",
    name: "Old Money Feminine",
    personalityLabel: "Quiet Luxury Heiress",
    genderScope: "FEMALE",
    category: "Luxury Classic",
    description: "Understated wealth in refined fabrics and silhouettes.",
    keywords: ["quiet luxury", "classic", "luxury"],
    clothingDNA: "Cashmere knits, wool trousers, silk shirts, pearl details, tailored coats.",
    hairstyleDNA: "Blow-dried waves, polished ponytail, or classic chignon.",
    shoesDNA: "Leather loafers, pointed flats, low block heels, riding boots.",
    colorDNA: ["cream", "navy", "camel", "ivory", "bottle green"],
    avoidDNA: "flashy logos, synthetic fabrics, overly revealing cuts",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "romantic-feminine",
    name: "Romantic Feminine",
    personalityLabel: "Modern Romantic",
    genderScope: "FEMALE",
    category: "Romantic",
    description: "Soft, flowing pieces with delicate, feminine details.",
    keywords: ["romantic", "soft", "elegant"],
    clothingDNA: "Floral midi dresses, puff sleeves, lace accents, soft knits, A-line skirts.",
    hairstyleDNA: "Soft curls, half-up styles, braided details, or wispy updo.",
    shoesDNA: "Strappy sandals, ballet flats, kitten heels, embroidered flats.",
    colorDNA: ["blush", "ivory", "sage green", "lavender", "soft rose"],
    avoidDNA: "boxy oversized cuts, harsh black leather, rigid tailoring",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "street-fashion",
    name: "Street Fashion",
    personalityLabel: "Urban Trendsetter",
    genderScope: "FEMALE",
    category: "Urban",
    description: "Bold, confident street style with contemporary references.",
    keywords: ["urban", "cool", "trend"],
    clothingDNA: "Oversized hoodies, cargo pants, crop tops, bomber jackets, statement accessories.",
    hairstyleDNA: "Sleek high ponytail, wolf cut, space buns, or blunt bangs.",
    shoesDNA: "Chunky sneakers, combat boots, high-top canvas, platform shoes.",
    colorDNA: ["black", "gray", "white", "neon green", "brown"],
    avoidDNA: "delicate florals, preppy pearls, bodycon dresses",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "office-professional",
    name: "Office Professional",
    personalityLabel: "Power Woman",
    genderScope: "FEMALE",
    category: "Business",
    description: "Sharp, confident tailoring for the modern workplace.",
    keywords: ["professional", "confident", "modern"],
    clothingDNA: "Tailored blazers, wide-leg trousers, sheath dresses, silk blouses, pencil skirts.",
    hairstyleDNA: "Sleek low bun, straight blowout, or polished shoulder-length cut.",
    shoesDNA: "Pointed pumps, loafers, block-heel mules, leather ankle boots.",
    colorDNA: ["navy", "black", "white", "burgundy", "camel"],
    avoidDNA: "denim, sneakers, overly casual knits, mini lengths",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "japanese-natural",
    name: "Japanese Natural",
    personalityLabel: "Natural Minimalist",
    genderScope: "FEMALE",
    category: "Natural",
    description: "Relaxed, natural textures with soft, earthy layers.",
    keywords: ["natural", "relaxed", "soft"],
    clothingDNA: "Linen dresses, cotton tunics, wide pants, oversized knits, earth-tone layers.",
    hairstyleDNA: "Natural waves, low bun with loose strands, or blunt straight bob.",
    shoesDNA: "Leather sandals, canvas sneakers, wooden clogs, minimal flats.",
    colorDNA: ["beige", "olive", "brown", "off-white", "rust"],
    avoidDNA: "synthetic shine, neon colors, tight bodycon silhouettes",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "y2k-trend",
    name: "Y2K Trend",
    personalityLabel: "Digital Nostalgic",
    genderScope: "FEMALE",
    category: "Trend",
    description: "Playful, nostalgic noughties energy with a modern twist.",
    keywords: ["youth", "trend", "fashion"],
    clothingDNA: "Low-rise jeans, baby tees, cargo skirts, halter tops, denim-on-denim, butterfly clips.",
    hairstyleDNA: "High pigtails, face-framing tendrils, crimped texture, or chunky highlights.",
    shoesDNA: "Platform sandals, colorful sneakers, kitten heels, ballet flats.",
    colorDNA: ["silver", "pink", "baby blue", "lavender", "denim"],
    avoidDNA: "classic tailoring, dark mature tones, heavy luxury branding",
    imagePromptTemplate: BASE_PROMPT,
  }),
  defineArchetype({
    slug: "active-lifestyle",
    name: "Active Lifestyle",
    personalityLabel: "Sporty Optimist",
    genderScope: "FEMALE",
    category: "Sporty",
    description: "Athleisure and activewear styled with healthy energy.",
    keywords: ["sporty", "healthy", "dynamic"],
    clothingDNA: "Matching sets, leggings, cropped jackets, oversized hoodies, tennis skirts.",
    hairstyleDNA: "High ponytail, sleek braids, claw-clip bun, or natural air-dried texture.",
    shoesDNA: "Running shoes, retro trainers, chunky sneakers, slides.",
    colorDNA: ["white", "black", "sage green", "blush", "navy"],
    avoidDNA: "formal dresses, high heels, delicate fabrics, heavy jewelry",
    imagePromptTemplate: BASE_PROMPT,
  }),
];

export const ALL_ARCHETYPES: ArchetypeDefinition[] = [...MALE_ARCHETYPES, ...FEMALE_ARCHETYPES];
